"""add oauth pending state table

Revision ID: ec32c4aee222
Revises: 76b19b9a6647
Create Date: 2026-08-30 15:53:33.567653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec32c4aee222'
down_revision: Union[str, Sequence[str], None] = '76b19b9a6647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usql_oauth_pending',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('verifier', sa.String(length=128), nullable=False),
    sa.Column('loopback_callback', sa.String(length=2048), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usql_oauth_pending')
    # ### end Alembic commands ###
